Prepend I/O thread names with configured gateway name.
kaazing/gateway pull request #920
Opened 2017-05-16 17:13 UTC by Anisotrop

2017-05-17 00:11 UTC, dpwspoon commented
@Anisotrop can you provide a sample output before and after, thanks!

2017-05-17 09:37 UTC, Anisotrop commented
Example before:
```
/usr/lib/jvm/java-8-openjdk-amd64/bin/java -ea -javaagent:/home/osboxes/SystemProjects/btrace/build/btrace-agent.jar=script=/home/osboxes/SystemProjects/btrace/com/sun/btrace/samples/AllCalls.class -Didea.test.cyclic.buffer.size=41943040 -javaagent:/opt/intellij-idea-community.2017.1.1/lib/idea_rt.jar=38204:/opt/intellij-idea-community.2017.1.1/bin -Dfile.encoding=UTF-8 -classpath /opt/intellij-idea-community.2017.1.1/lib/idea_rt.jar:/opt/intellij-idea-community.2017.1.1/plugins/junit/lib/junit-rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/icedtea-sound.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/management-agent.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar:/home/osboxes/IdeaProjects/enterprise.gateway/transport/socks/target/test-classes:/home/osboxes/IdeaProjects/enterprise.gateway/transport/socks/target/classes:/home/osboxes/IdeaProjects/enterprise.gateway/resource.address/socks/target/classes:/home/osboxes/.m2/repository/org/kaazing/gateway.resource.address/develop-SNAPSHOT/gateway.resource.address-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.util/develop-SNAPSHOT/gateway.util-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.transport/develop-SNAPSHOT/gateway.transport-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.security/develop-SNAPSHOT/gateway.security-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/mina.netty/develop-SNAPSHOT/mina.netty-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/agrona/Agrona/0.9.1/Agrona-0.9.1.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.server/develop-SNAPSHOT/gateway.server-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.service/develop-SNAPSHOT/gateway.service-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/com/hazelcast/hazelcast/3.7.4/hazelcast-3.7.4.jar:/home/osboxes/.m2/repository/com/hazelcast/hazelcast-client/3.7.4/hazelcast-client-3.7.4.jar:/home/osboxes/.m2/repository/com/hazelcast/hazelcast-aws/1.1.1/hazelcast-aws-1.1.1.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.resource.address.http/develop-SNAPSHOT/gateway.resource.address.http-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.server.api/develop-SNAPSHOT/gateway.server.api-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.server.spi/develop-SNAPSHOT/gateway.server.spi-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/apache/xmlbeans/xmlbeans/2.4.0/xmlbeans-2.4.0.jar:/home/osboxes/.m2/repository/stax/stax-api/1.0.1/stax-api-1.0.1.jar:/home/osboxes/.m2/repository/org/jdom/jdom/1.1/jdom-1.1.jar:/home/osboxes/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar:/home/osboxes/.m2/repository/org/slf4j/slf4j-log4j12/1.7.21/slf4j-log4j12-1.7.21.jar:/home/osboxes/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/home/osboxes/.m2/repository/net/sf/opencsv/opencsv/2.3/opencsv-2.3.jar:/home/osboxes/.m2/repository/org/json/json/20090211/json-20090211.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.resource.address.pipe/develop-SNAPSHOT/gateway.resource.address.pipe-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.resource.address.httpxe/develop-SNAPSHOT/gateway.resource.address.httpxe-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.transport.pipe/develop-SNAPSHOT/gateway.transport.pipe-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.transport.bio/develop-SNAPSHOT/gateway.transport.bio-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.resource.address.udp/develop-SNAPSHOT/gateway.resource.address.udp-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.service.echo/develop-SNAPSHOT/gateway.service.echo-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.service.proxy/develop-SNAPSHOT/gateway.service.proxy-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.transport.nio/develop-SNAPSHOT/gateway.transport.nio-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.resource.address.tcp/develop-SNAPSHOT/gateway.resource.address.tcp-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/test.util/develop-SNAPSHOT/test.util-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.transport.wsn/develop-SNAPSHOT/gateway.transport.wsn-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.resource.address.wsn/develop-SNAPSHOT/gateway.resource.address.wsn-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.resource.address.ws/develop-SNAPSHOT/gateway.resource.address.ws-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.transport.ws/develop-SNAPSHOT/gateway.transport.ws-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.transport.wseb/develop-SNAPSHOT/gateway.transport.wseb-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.resource.address.wse/develop-SNAPSHOT/gateway.resource.address.wse-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.transport.http/develop-SNAPSHOT/gateway.transport.http-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.transport.ssl/develop-SNAPSHOT/gateway.transport.ssl-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.resource.address.ssl/develop-SNAPSHOT/gateway.resource.address.ssl-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/k3po.junit/3.0.0-alpha-65/k3po.junit-3.0.0-alpha-65.jar:/home/osboxes/.m2/repository/org/kaazing/net.tcp/1.1.0.9/net.tcp-1.1.0.9.jar:/home/osboxes/.m2/repository/org/kaazing/net.api/1.1.0.9/net.api-1.1.0.9.jar:/home/osboxes/.m2/repository/org/kaazing/community.license/2.18/community.license-2.18.jar:/home/osboxes/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/osboxes/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/osboxes/.m2/repository/org/jmock/jmock/2.6.0/jmock-2.6.0.jar:/home/osboxes/.m2/repository/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar:/home/osboxes/.m2/repository/org/jmock/jmock-legacy/2.6.0/jmock-legacy-2.6.0.jar:/home/osboxes/.m2/repository/org/objenesis/objenesis/1.0/objenesis-1.0.jar:/home/osboxes/.m2/repository/cglib/cglib-nodep/2.1_3/cglib-nodep-2.1_3.jar:/home/osboxes/.m2/repository/com/kaazing/gateway/com.kaazing.gateway.truststore.tests/1.0.0.16/com.kaazing.gateway.truststore.tests-1.0.0.16-keystore.jar:/home/osboxes/.m2/repository/com/kaazing/gateway/com.kaazing.gateway.truststore/1.0.0.54/com.kaazing.gateway.truststore-1.0.0.54.jar:/home/osboxes/.m2/repository/com/kaazing/specification.sock5plus/1.0.1/specification.sock5plus-1.0.1.jar:/home/osboxes/.m2/repository/org/kaazing/k3po.lang/5.0.6/k3po.lang-5.0.6.jar:/home/osboxes/.m2/repository/org/antlr/antlr4-runtime/4.2.2/antlr4-runtime-4.2.2.jar:/home/osboxes/.m2/repository/org/abego/treelayout/org.abego.treelayout.core/1.0.1/org.abego.treelayout.core-1.0.1.jar:/home/osboxes/.m2/repository/org/antlr/antlr4-annotations/4.2.2/antlr4-annotations-4.2.2.jar:/home/osboxes/.m2/repository/de/odysseus/juel/juel-ap [...]

2017-05-17 09:42 UTC, Anisotrop commented
After the changes, with `gateway1` and `gateway2` appearing in the `New I/O worker` threads. This is done by adding `.property(DEBUG_GATEWAY_NAME.getPropertyName(), "gatewayX")` to the `GatewayConfigurationBuilder`:

```
/usr/lib/jvm/java-8-openjdk-amd64/bin/java -ea -javaagent:/home/osboxes/SystemProjects/btrace/build/btrace-agent.jar=script=/home/osboxes/SystemProjects/btrace/com/sun/btrace/samples/AllCalls.class -Didea.test.cyclic.buffer.size=41943040 -javaagent:/opt/intellij-idea-community.2017.1.1/lib/idea_rt.jar=37470:/opt/intellij-idea-community.2017.1.1/bin -Dfile.encoding=UTF-8 -classpath /opt/intellij-idea-community.2017.1.1/lib/idea_rt.jar:/opt/intellij-idea-community.2017.1.1/plugins/junit/lib/junit-rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/icedtea-sound.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/management-agent.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/lib/tools.jar:/home/osboxes/IdeaProjects/enterprise.gateway/transport/socks/target/test-classes:/home/osboxes/IdeaProjects/enterprise.gateway/transport/socks/target/classes:/home/osboxes/IdeaProjects/enterprise.gateway/resource.address/socks/target/classes:/home/osboxes/.m2/repository/org/kaazing/gateway.resource.address/develop-SNAPSHOT/gateway.resource.address-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.util/develop-SNAPSHOT/gateway.util-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.transport/develop-SNAPSHOT/gateway.transport-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.security/develop-SNAPSHOT/gateway.security-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/mina.netty/develop-SNAPSHOT/mina.netty-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/agrona/Agrona/0.9.1/Agrona-0.9.1.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.server/develop-SNAPSHOT/gateway.server-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.service/develop-SNAPSHOT/gateway.service-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/com/hazelcast/hazelcast/3.7.4/hazelcast-3.7.4.jar:/home/osboxes/.m2/repository/com/hazelcast/hazelcast-client/3.7.4/hazelcast-client-3.7.4.jar:/home/osboxes/.m2/repository/com/hazelcast/hazelcast-aws/1.1.1/hazelcast-aws-1.1.1.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.resource.address.http/develop-SNAPSHOT/gateway.resource.address.http-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.server.api/develop-SNAPSHOT/gateway.server.api-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.server.spi/develop-SNAPSHOT/gateway.server.spi-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/apache/xmlbeans/xmlbeans/2.4.0/xmlbeans-2.4.0.jar:/home/osboxes/.m2/repository/stax/stax-api/1.0.1/stax-api-1.0.1.jar:/home/osboxes/.m2/repository/org/jdom/jdom/1.1/jdom-1.1.jar:/home/osboxes/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar:/home/osboxes/.m2/repository/org/slf4j/slf4j-log4j12/1.7.21/slf4j-log4j12-1.7.21.jar:/home/osboxes/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/home/osboxes/.m2/repository/net/sf/opencsv/opencsv/2.3/opencsv-2.3.jar:/home/osboxes/.m2/repository/org/json/json/20090211/json-20090211.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.resource.address.pipe/develop-SNAPSHOT/gateway.resource.address.pipe-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.resource.address.httpxe/develop-SNAPSHOT/gateway.resource.address.httpxe-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.transport.pipe/develop-SNAPSHOT/gateway.transport.pipe-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.transport.bio/develop-SNAPSHOT/gateway.transport.bio-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.resource.address.udp/develop-SNAPSHOT/gateway.resource.address.udp-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.service.echo/develop-SNAPSHOT/gateway.service.echo-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.service.proxy/develop-SNAPSHOT/gateway.service.proxy-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.transport.nio/develop-SNAPSHOT/gateway.transport.nio-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.resource.address.tcp/develop-SNAPSHOT/gateway.resource.address.tcp-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/test.util/develop-SNAPSHOT/test.util-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.transport.wsn/develop-SNAPSHOT/gateway.transport.wsn-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.resource.address.wsn/develop-SNAPSHOT/gateway.resource.address.wsn-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.resource.address.ws/develop-SNAPSHOT/gateway.resource.address.ws-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.transport.ws/develop-SNAPSHOT/gateway.transport.ws-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.transport.wseb/develop-SNAPSHOT/gateway.transport.wseb-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.resource.address.wse/develop-SNAPSHOT/gateway.resource.address.wse-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.transport.http/develop-SNAPSHOT/gateway.transport.http-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.transport.ssl/develop-SNAPSHOT/gateway.transport.ssl-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/gateway.resource.address.ssl/develop-SNAPSHOT/gateway.resource.address.ssl-develop-SNAPSHOT.jar:/home/osboxes/.m2/repository/org/kaazing/k3po.junit/3.0.0-alpha-65/k3po.junit-3.0.0-alpha-65.jar:/home/osboxes/.m2/repository/org/kaazing/net.tcp/1.1.0.9/net.tcp-1.1.0.9.jar:/home/osboxes/.m2/repository/org/kaazing/net.api/1.1.0.9/net.api-1.1.0.9.jar:/home/osboxes/.m2/repository/org/kaazing/community.license/2.18/community.license-2.18.jar:/home/osboxes/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/osboxes/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/osboxes/.m2/repository/org/jmock/jmock/2.6.0/jmock-2.6.0.jar:/home/osboxes/.m2/repository/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar:/home/osboxes/.m2/repository/org/jmock/jmock-legacy/2.6.0/jmock-legacy-2.6.0.jar:/home/osboxes/.m2/repository/org/objenesis/objenesis/1.0/objenesis-1.0.jar:/home/osboxes/.m2/repository/cglib/cglib-nodep/2.1_3/cglib-nodep-2.1_3.jar:/home/osboxes/.m2/repository/com/kaazing/gateway/com.kaazing.gateway.truststore.tests/1.0.0.16/com.kaazing.gateway.truststore.tests-1.0.0.16-keystore.jar:/home/osboxes/.m2/repository/com/kaazing/gateway/com.kaazing.gateway.truststore/1.0.0.54/com.kaazing.gateway.truststore-1.0.0.54.jar:/home/osboxes/.m2/repository/com/kaazing/specification.sock5plus/1.0.1/specification.sock5plus-1.0.1.jar:/home/osboxes/.m2/repository/org/kaazing/k3po.lang/5.0.6/k3po.lang-5.0.6.jar:/home/osboxes/.m2/repository/org/antlr/antlr4-runtime/4.2.2/antlr4-runtime-4.2.2.jar:/home/osboxes/.m2/repository/org/abego/treelayout/org.abego.tre [...]

2017-05-17 20:52 UTC, dpwspoon commented
LGTM, @cmebarrow are you ok with this change

2017-06-06 21:10 UTC, cmebarrow requested changes
If you can't find a way to make it work for embedded gateway it's not a show stopper, just would be better if you can

2017-06-06 21:10 UTC, cmebarrow commented on transport/nio/src/main/java/org/kaazing/gateway/transport/nio/internal/socket/NioSocketAcceptor.java
> +            final String gatewayDebugName = GATEWAY_IDENTIFIER.getProperty(configuration);
I would recommend renaming the variable to gatewayIdentifier for clarity, since this isn't related to debugging, or to the use of debug log level, it will generally affect all log messages on the I/O threads.

2017-06-06 21:10 UTC, cmebarrow commented on transport/nio/src/main/java/org/kaazing/gateway/transport/nio/internal/socket/NioSocketAcceptor.java
> +import static org.kaazing.gateway.util.InternalSystemProperty.GATEWAY_IDENTIFIER;
Using a system property will not work for embedded gateway use, where more than one gateway can potentially run in the same Java process. Would it be possible to pass in the gateway identifier as a parameter when gateway is running embedded?

2017-06-26 13:38 UTC, closed without merging